### ISSUE TITLE
unable to verify the first certificate 续，用相同的原理解决node-gyp的问题

### ISSUE THREAD

**Issue by p2227** [p2227/p2227.github.io#8]
此文章是 #5 的后续

在安装node-canvas的时候，也总是提示这个，不同的是，这次提示错误 的地方找不到源代码的所在地

```
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack at Error (native)
gyp ERR! stack at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
gyp ERR! stack at emitNone (events.js:67:13)
gyp ERR! stack at TLSSocket.emit (events.js:166:7)
gyp ERR! stack at TLSSocket._finishInit (_tls_wrap.js:585:8)
```

这个_tls_wrap.js在哪里，要整个电脑去搜索吗？

思考了一会之后，根据上一次的总结，这肯定是一个https的问题，要是想知道是哪个https连接有问题是比较麻烦的。但是如果这样google

```
node-gyp strict ssl
```

会很快找到issus
`try invoking node-gyp with NODE_TLS_REJECT_UNAUTHORIZED=0.`

于是设置环境变量，安装~~~~一切正常

**Comment by NineF** [comment]
请问NODE_TLS_REJECT_UNAUTHORIZED=0  这个是在哪点设置啊，找了半天没发现。。。

**Comment by NineF** [comment]
。。被自己蠢到了。。找半天找不到怎样设置。。。突然记起打开node-gyp。。设置了process.env.NODE_TLS_REJECT_UNAUTHORIZED=“0”就可以了。。谢谢了

**Comment by leikao** [comment]
设置如下环境变量：
`export NODE_TLS_REJECT_UNAUTHORIZED=0` 也可以顺利解决 :)

**Comment by liujiaqi222** [comment]
这个环境变量需要在哪里设置，我应该在哪里写process.env.NODE_TLS_REJECT_UNAUTHORIZED=“0”
